# 端口号
server:
  port: 8888
# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8
    username: root
    password: 123456
    # 当你将应用部署于应用服务器上的时候想让数据源由应用服务器管理，
    # 那么可以使用如下配置方式引入JNDI数据源。
#    jndi-name: java:jboss/datasources/customers
